/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.JLabel;

/**
 *
 * @author kario
 */
public class StudentLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private int w = 700;
    private int h = 450;
    JLabel l = new JLabel();
    public StudentLogin() {
        initComponents();
        setSize(w, h);
        setLocationRelativeTo(null);
        setTitle("Welcome back");
        l = lblLogo;
//        l.lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users/User_Group_Icon_256.png")));
//        setIconImage(new ImageIcon(getClass().getResource("../img/icon.PNG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernamepanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        buttonPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        logoPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        contentPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setMinimumSize(new java.awt.Dimension(51, 40));
        titlePanel.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Chilanka", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome Back!");
        titlePanel.add(lblTitle, java.awt.BorderLayout.CENTER);
        titlePanel.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        contentPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        formPanel.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jLabel2.setFont(new java.awt.Font("Chilanka", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Let us Login !");
        formPanel.add(jLabel2);

        usernamepanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1. Enter Your Names !");
        usernamepanel.add(jLabel3, java.awt.BorderLayout.NORTH);

        txtUsername.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        txtUsername.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        usernamepanel.add(txtUsername, java.awt.BorderLayout.CENTER);

        jLabel4.setPreferredSize(new java.awt.Dimension(20, 0));
        usernamepanel.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jLabel5.setPreferredSize(new java.awt.Dimension(20, 0));
        usernamepanel.add(jLabel5, java.awt.BorderLayout.LINE_START);

        formPanel.add(usernamepanel);

        passwordpanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2. Enter Your Password!");
        passwordpanel.add(jLabel6, java.awt.BorderLayout.NORTH);

        jLabel7.setPreferredSize(new java.awt.Dimension(20, 0));
        passwordpanel.add(jLabel7, java.awt.BorderLayout.LINE_END);

        jLabel8.setPreferredSize(new java.awt.Dimension(20, 0));
        passwordpanel.add(jLabel8, java.awt.BorderLayout.LINE_START);

        pwdPassword.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });
        passwordpanel.add(pwdPassword, java.awt.BorderLayout.CENTER);

        formPanel.add(passwordpanel);

        buttonPanel.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("3. Press Login!");
        buttonPanel.add(jLabel10, java.awt.BorderLayout.NORTH);

        btnLogin.setFont(new java.awt.Font("Chilanka", 0, 8)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setPreferredSize(new java.awt.Dimension(75, 50));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);

        jButton4.setFont(new java.awt.Font("Chilanka", 0, 8)); // NOI18N
        jButton4.setText("forgotten Password?");
        jButton4.setPreferredSize(new java.awt.Dimension(235, 50));
        jPanel1.add(jButton4);

        btnExit.setFont(new java.awt.Font("Chilanka", 0, 8)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(69, 50));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);

        buttonPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        formPanel.add(buttonPanel);

        contentPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        logoPanel.setBackground(new java.awt.Color(129, 255, 255));
        logoPanel.setForeground(new java.awt.Color(255, 255, 255));
        logoPanel.setPreferredSize(new java.awt.Dimension(260, 100));
        logoPanel.setLayout(new java.awt.BorderLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users/Mickey_V2.png"))); // NOI18N
        logoPanel.add(lblLogo, java.awt.BorderLayout.CENTER);

        getContentPane().add(logoPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Validator v = new Validator();

        String username = txtUsername.getText().trim();
        String password = pwdPassword.getText().trim();

        String[] uname_valid = v.nameValidator(username, "User name");
        String[] pword_valid = v.passwordValidator(password);

        if (uname_valid[0] == "true" && pword_valid[0] == "true") {
            Database db = new Database();
            String sql = "SELECT"
                    + "    `Student_ID`,"
                    + "    `First_Name`,"
                    + "    `Last_Name`,"
                    + "    `Age`"
                    + "FROM"
                    + "    `student`"
                    + "WHERE"
                    + "    `UserName` = '" + username + "' && `Password` = '" + password + "'";
            String fname = "";
            String student_id = "";

            boolean user_exists = db.checkDuplicate(sql);

            if (user_exists == true) {
                ResultSet rs = db.executeSelect(sql);
                try {
                    while (rs.next()) {
                        fname = rs.getString("First_name");
                        student_id = rs.getString("Student_ID");

                        fname = fname + " " + rs.getString("Last_Name");
                        new StudentHome(fname, student_id).setVisible(true);
                        this.dispose();
                    }
                } catch (Exception e) {
                    System.out.println("Error : " + e);
                }
            } else {
                v.popup("Wrong Username/Password provided");
            }

        } else {
            if (uname_valid[0] == "false") {
                v.popup(uname_valid[1]);
            }
            if (pword_valid[0] == "false") {
                v.popup(pword_valid[1]);
            }
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         Create and display the dialog */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    StudentLogin dialog = new StudentLogin();
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
        } catch (Exception e) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    StudentLogin dialog = new StudentLogin();
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel passwordpanel;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel usernamepanel;
    // End of variables declaration//GEN-END:variables
}
